const mongoose = require("mongoose");

// One-time passwords: generated by OUR backend, sent via Fast2SMS, verified
// locally. (MSG91's classic OTP API cannot deliver SMS in India without a
// DLT-registered template, so the provider was switched — the Flutter app's
// API contract is unchanged.)
//
// Security:
// - otpHash: SHA256 of the code — plaintext OTP is NEVER stored.
// - expiresAt: TTL index auto-deletes the doc after expiry (5 min).
// - attempts: wrong-try counter; >5 attempts invalidates the OTP.
// - One active OTP per phone: a new send deletes the previous one.
const s = new mongoose.Schema({
  phone:     { type: String, required: true, index: true },
  otpHash:   { type: String, required: true },
  attempts:  { type: Number, default: 0 },
  createdAt: { type: Date, default: Date.now },
  expiresAt: { type: Date, required: true, index: { expires: 0 } },
});

s.statics.createForPhone = async function (phone, otpHash, ttlMs) {
  await this.deleteMany({ phone });
  return this.create({ phone, otpHash, attempts: 0, expiresAt: new Date(Date.now() + ttlMs) });
};

module.exports = mongoose.model("Otp", s);
